name: CI

on:
  push:
    branches:
      - main
      - master
    tags: ['*']
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}


env:
  CMDSTAN: "/home/worker/cmdstan-2.31.0/"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.8'
          #- '1.9-beta3'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        exclude:
          - os: windows-latest
            arch: x86
          - os: macOS-latest
            arch: x86
    steps:
      - name: Install extra dependency on main branch
        shell: julia --project=. {0}
        run: |
          println(pwd())
          println(ENV["CMDSTAN"])
          println(ENV["HOME"])
      - run: |
          OLDWD=`pwd`
          cd ~
          pwd
          wget https://github.com/stan-dev/cmdstan/releases/download/v2.31.0/cmdstan-2.31.0.tar.gz
          tar -xzpf cmdstan-2.31.0.tar.gz
          ls -lia .
          ls -lia ./cmdstan-2.31.0
          ls -lia ./cmdstan-2.31.0/make
          touch ./cmdstan-2.31.0/make/local
          echo "STAN_THREADS=true" > ./cmdstan-2.31.0/make/local
          cat ./cmdstan-2.31.0/make/local
          make -C $CMDSTAN build
          cd $OLDWD
        env:
          CMDSTAN: "/home/runner/cmdstan-2.31.0/"
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          CMDSTAN: "/home/runner/cmdstan-2.31.0/"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
